"""Add users table

Revision ID: 135bd550c4c5
Revises: 
Create Date: 2025-10-10 08:33:03.288485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135bd550c4c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###