"""Add soft delete to carpets

Revision ID: 9d32e6c0e83b
Revises: 135bd550c4c5
Create Date: 2025-10-14 14:22:54.196502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d32e6c0e83b'
down_revision = '135bd550c4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='حذف شده؟'))
    op.add_column('carpets', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='تاریخ حذف'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpets', 'deleted_at')
    op.drop_column('carpets', 'is_deleted')
    # ### end Alembic commands ###